# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/docs/Doxyfile.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/src/glfwConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/src/glfwConfigVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/glfw/tests/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CMakeConfigurableFile.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/FindDoxygen.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/FindThreads.cmake))

/Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -H/Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files -B/Users/williamcrupi/Downloads/Ex_Files_UaR_OpenGL/Exercise\ Files/xcode
